collab-project/videojs-record

src/js/videojs.record.js

close AudioContext on stop

---

.travis.yml
bower.json
package.json

change the main to include the js and css files for dependency injection

include css file for bower 

---

src/js/videojs.record.js

Filter elements added by prototype

Filter elements added by prototype

---

CHANGES.md
package-lock.json
src/js/engine/record-engine.js

Add compatibility for video.js v6.6.0

---

CHANGES.md
README.md
examples/plugins/audio-only-mp3.html
examples/plugins/audio-only-ogg.html
src/js/defaults.js
src/js/plugins/lamejs-plugin.js
src/js/plugins/libvorbis-plugin.js
src/js/videojs.record.js

ability to specify bitrate setting in lamejs plugin

---

CHANGES.md
src/js/videojs.record.js

fix issue with takePhoto in Chrome

---

CHANGES.md
package-lock.json
package.json
src/css/components/camera-button.scss
src/css/components/device-button.scss
src/css/components/record-indicator.scss
src/css/components/record-toggle.scss
src/css/fluid.scss
src/css/main.scss
src/js/videojs.record.js
test/videojs.record.spec.js

Add plugin style class

---

src/js/videojs.record.js

Allows loadOptions() method to receive an options parameter

---

CHANGES.md
README.md
package-lock.json
package.json
src/js/defaults.js
src/js/videojs.record.js
test/defaults.spec.js

Introduces a new `autoMuteDevice` option.
fixes #157

Turning off the device between recordings

---

CHANGES.md
examples/react/index.js
examples/upload/simple.html
src/js/engine/record-rtc.js
src/js/videojs.record.js
test/controls/camera-button.spec.js
test/controls/device-button.spec.js
test/controls/record-toggle.spec.js
test/utils/detect-browser.spec.js
test/videojs.record.spec.js

Remove player.recordedData.video (Chrome audio/video only)

---

.eslintrc.json
package-lock.json
package.json
src/js/utils/detect-browser.js
test/controls/animation-display.spec.js
test/controls/camera-button.spec.js
test/controls/device-button.spec.js
test/controls/record-canvas.spec.js
test/controls/record-indicator.spec.js
test/controls/record-toggle.spec.js
test/defaults.spec.js
test/engine/record-engine.spec.js
test/engine/record-mode.spec.js
test/plugins/lamejs-plugin.spec.js
test/plugins/libvorbis-plugin.spec.js
test/plugins/opus-recorder-plugin.spec.js
test/plugins/recorderjs-plugin.spec.js
test/test-helpers.js
test/utils/browser-shim.spec.js
test/utils/detect-browser.spec.js
test/utils/format-time.spec.js
test/videojs.record.spec.js

More tests

---

CHANGES.md
README.md
package-lock.json
package.json
src/js/defaults.js
src/js/videojs.record.js
test/defaults.spec.js

add msDisplayMax option

---

CHANGES.md
examples/audio-only.html
examples/change-audio-input.html
examples/change-audio-output.html
examples/enumerate-devices.html
examples/plugins/audio-only-mp3.html
examples/plugins/audio-only-ogg.html
examples/plugins/audio-only-opus.html
examples/plugins/audio-only-recorderjs.html
examples/upload/fine-uploader.html
examples/upload/jquery.fileupload.html
package-lock.json
package.json

for microphone support in the MS Edge browser

Bump required videojs-wavesurfer version to 2.6.0

---

.travis.yml
CHANGES.md
README.md
src/js/defaults.js
src/js/videojs.record.js
test/defaults.spec.js

add maxFileSize option

---

CHANGES.md
build-config/fragments/dev.js
package-lock.json
package.json
src/js/videojs.record.js

Improve plugin destroy

---

.travis.yml
CHANGES.md
bower.json
build-config/fragments/dev.js
karma.conf.js
package-lock.json
package.json
src/js/utils/browser-shim.js
src/js/videojs.record.js
test/utils/browser-shim.spec.js

Improve setSrcObject

---

.travis.yml
CHANGES.md
karma.conf.js
package-lock.json
src/js/videojs.record.js
test/test-helpers.js

make sure to reset srcObject

---

CHANGES.md
README.md
build-config/fragments/plugins.js
examples/plugins/video-only-ebml.html
package-lock.json
package.json
src/js/defaults.js
src/js/engine/convert-engine.js
src/js/engine/engine-loader.js
src/js/engine/loader.js
src/js/engine/record-engine.js
src/js/plugins/ts-ebml-plugin.js
src/js/utils/file-util.js
src/js/videojs.record.js
test/defaults.spec.js
test/engine/convert-engine.spec.js
test/engine/record-engine.spec.js
test/plugins/ts-ebml-plugin.spec.js
test/test-helpers.js

ts-ebml convert plugin: inject webm metadata

---

CHANGES.md
README.md
bower.json
examples/audio-only.html
examples/audio-video.html
examples/browser-workarounds.js
examples/change-audio-input.html
examples/change-audio-output.html
examples/enumerate-devices.html
examples/plugins/audio-only-lamejs.html
examples/plugins/audio-only-mp3.html
examples/plugins/audio-only-ogg.html
examples/plugins/audio-only-opus.html
examples/plugins/audio-only-recorderjs.html
examples/plugins/video-only-ebml.html
examples/react/index.js
examples/screen-only.html
examples/upload/fine-uploader.html
examples/upload/jquery.fileupload.html
examples/upload/simple.html
examples/upload/websocket.html
examples/video-only.html
package-lock.json
package.json
test/videojs.record.spec.js

fixes #181 
requires updated recordrtc (5.5.2).

support for video recording in Safari

---

CHANGES.md
README.md
examples/change-audio-input.html
examples/change-audio-output.html
examples/change-video-input.html
src/js/videojs.record.js

add change video input example

---

CHANGES.md
src/js/controls/camera-button.js
src/js/controls/picture-in-picture-toggle.js
src/js/controls/record-indicator.js
src/js/controls/record-toggle.js
src/js/engine/record-engine.js
src/js/engine/record-rtc.js
src/js/event.js
src/js/videojs.record.js
test/controls/camera-button.spec.js
test/controls/device-button.spec.js
test/controls/record-toggle.spec.js
test/engine/record-engine.spec.js
test/plugins/lamejs-plugin.spec.js
test/plugins/libvorbis-plugin.spec.js
test/plugins/opus-recorder-plugin.spec.js
test/plugins/recorderjs-plugin.spec.js
test/plugins/ts-ebml-plugin.spec.js
test/plugins/vmsg-plugin.spec.js
test/plugins/webm-wasm-plugin.spec.js

move event types to separate class

---

CHANGES.md
package-lock.json
package.json
src/js/videojs.record.js

fix suspended wavesurfer.js AudioContext in Chrome

---

CHANGES.md
package-lock.json
package.json
src/js/engine/record-rtc.js

add recordrtc import

---

CHANGES.md
README.md
examples/hot-keys.html
package-lock.json
package.json
src/js/defaults.js
src/js/hot-keys.js
src/js/videojs.record.js
test/defaults.spec.js

add support for keyboard hotkeys

---

CHANGES.md
README.md
examples/animated-gif.html
examples/audio-video.html
examples/change-video-input.html
examples/hot-keys.html
examples/image-only.html
examples/picture-in-picture.html
examples/plugins/video-only-ebml.html
examples/plugins/video-only-webm-wasm.html
examples/react/index.js
examples/video-only.html
src/js/videojs.record.js

trigger error when getUserMedia support is missing

---

CHANGES.md
README.md
examples/assets/css/examples.css
examples/change-audio-input.html
examples/change-audio-output.html
examples/change-video-input.html
src/js/videojs.record.js
test/plugins/webm-wasm-plugin.spec.js
test/test-helpers.js

add setVideoInput and setAudioInput

---

CHANGES.md
examples/picture-in-picture.html
src/js/utils/compare-version.js
src/js/videojs.record.js
test/utils/compare-version.spec.js

support video.js picture-in-picture API (introduced in video.js 7.6.0)

---

CHANGES.md
package.json

also add `style` and `sass` entries to `package.json`.

Specify non-minified videojs-record in main entry of package.json

---

CHANGES.md
src/js/videojs.record.js

check for pipToggle existence

---

CHANGES.md
src/js/videojs.record.js

to prevent screwing up other players on the page.
fixes #437

move monkey-patched play method into plugin constructor

---

README.md

Add link to Vue wiki page in README.

---

CHANGES.md
docs/recorded-data.md
src/js/engine/convert-engine.js
src/js/engine/record-engine.js
src/js/videojs.record.js

add support for downloading converted data using saveAs

---

docs/demo/audio-only-ffmpegjs.html
docs/demo/audio-only-lamejs.html
docs/demo/audio-only-mp3.html
docs/demo/audio-only-ogg.html
docs/demo/audio-only-opus-media-recorder.html
docs/demo/audio-only-opus.html
docs/demo/audio-only-recorderjs.html
docs/demo/audio-only.html
docs/demo/change-audio-input.html
docs/demo/change-audio-output.html
docs/demo/enumerate-devices.html
docs/usage.md
examples/audio-only.html
examples/change-audio-input.html
examples/change-audio-output.html
examples/enumerate-devices.html
examples/plugins/audio-only-ffmpegjs.html
examples/plugins/audio-only-lamejs.html
examples/plugins/audio-only-mp3.html
examples/plugins/audio-only-ogg.html
examples/plugins/audio-only-opus-media-recorder.html
examples/plugins/audio-only-opus.html
examples/plugins/audio-only-recorderjs.html
examples/upload/fine-uploader.html
examples/upload/jquery.fileupload.html
examples/upload/websocket.html

examples: enable videojs-wavesurfer displayMilliseconds option

---

CHANGES.md
docs/controls.md
docs/methods.md
docs/options.md
package-lock.json
package.json
src/js/defaults.js
src/js/videojs.record.js
test/defaults.spec.js
test/videojs.record.spec.js

add formatTime option

---

CHANGES.md
src/css/main.scss

fix controlbar flickering in Mobile Safari

---

.github/workflows/main.yml
CHANGES.md
src/js/videojs.record.js

fix hiding picture-in-picture button

---

CHANGES.md
docs/demo/image-only.html
docs/media-constraints.md
examples/image-only.html
src/js/videojs.record.js
test/test-helpers.js
test/videojs.record.spec.js

image-only: fix aspect ratio of canvas drawing

---

src/js/videojs.record.js

fix stopping stream if it is active when using `getDevice`

---

CHANGES.md
src/js/videojs.record.js

improve check in removeRecording

---

CHANGES.md
docs/methods.md
docs/options.md
docs/recorded-data.md
src/js/defaults.js
src/js/videojs.record.js
test/defaults.spec.js

add convertAuto option

---

CHANGES.md
src/js/plugins/ts-ebml-plugin.js

ts-ebml plugin: add fix for Safari

---

docs/package-lock.json
docs/package.json

upgrade @ffmpeg/core from 0.11.0 to 0.12.2.

fix: upgrade @ffmpeg/core from 0.11.0 to 0.12.2

---

CHANGES.md
src/css/components/record-indicator.scss

ignore click events for record indicator
